# Generated by Django 2.2.24 on 2021-09-26 11:08

from django.db import migrations, models
import djongo.models.fields
import quickstart.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('symbol', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('bids', djongo.models.fields.ArrayField(model_container=quickstart.models.Bid)),
                ('asks', djongo.models.fields.ArrayField(model_container=quickstart.models.Ask)),
            ],
        ),
    ]
